language: ruby

rvm:
 - 2.3.3

addons:
  postgresql: '9.4'

git:
  submodules: false

env:
  SECRET_KEY_BASE="$(bundle exec rake secret)"

before_script:
  - psql -c 'create database free_sms_test;' -U postgres

script:
 - bundle exec rubocop
 - bundle exec rspec